[build]
  # Tell Netlify to run the build from the "devrandom" subdirectory
  base = "devrandom" 
  
  # Standard command to install dependencies and build an Astro site
  command = "npm install && npm run build"
  
  # The publish directory is now relative to the base directory
  publish = "dist"